fun main() {
    val employee = Employee()
    employee.setFullName("Фирсова Алиса Антоновна")
    employee.setPosition("Разработчик")
    employee.setSalary(75000)
    employee.setYearsOfExperience(3)
    employee.displayInfo()
    employee.setSalary(-10000)
    employee.setYearsOfExperience(-3)
    println("Текущий опыт: ${employee.getYearsOfExperience()}")
    employee.setYearsOfExperience(60)
    println("Текущий опыт: ${employee.getYearsOfExperience()}")

    println("Текущая зарплата: ${employee.getSalary()}")
    println("Информация о сотруднике:")
    println("ФИО: ${employee.getFullName()}")
    println("Должность: ${employee.getPosition()}")
    println("Зарплата: ${employee.getSalary()}")
    println("Опыт работы: ${employee.getYearsOfExperience()} лет")
    employee.displayInfo()
}